spring.application.name=Vignettes
spring.jpa.open-in-view=false
spring.flyway.enabled=false
spring.datasource.url=jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS COMMUNITY
spring.jpa.hibernate.ddl-auto=create-drop
###
springdoc.swagger-ui.path=/api/docs
springdoc.api-docs.path=/api/docs/openapi
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=false
springdoc.override-with-generic-response=false
springdoc.swagger-ui.tagsSorter=alpha
###
app.jwt.secret=${APP_JWT_SECRET}
app.storage.root=${APP_STORAGE_ROOT:./data/storage}
###
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB