create table scenario_history_entry
(
    id             BIGINT generated by default as identity primary key,
    scenario_id    BIGINT                   not null,
    actor_user_id  BIGINT                   not null,
    actor_username VARCHAR(255)             not null,
    action         VARCHAR(50)              not null,
    summary        VARCHAR(500)             not null,
    created_at     TIMESTAMP WITH TIME ZONE not null
);

create index idx_scenario_history_entry_scenario on scenario_history_entry (scenario_id, created_at desc);
