create table discussion_message
(
    id                BIGINT generated by default as identity primary key,
    target_type       VARCHAR(50)              not null,
    target_id         VARCHAR(255)             not null,
    parent_message_id BIGINT,
    author_id         BIGINT                   not null,
    content           VARCHAR(4000)            not null,
    contribution_type VARCHAR(50)              not null,
    created_at        TIMESTAMP WITH TIME ZONE not null
);

create index idx_discussion_target on discussion_message (target_type, target_id, created_at);

create index idx_discussion_parent on discussion_message (parent_message_id);

create table accreditation_request
(
    id                   BIGINT generated by default as identity primary key,
    requested_by_user_id BIGINT                   not null,
    scope_type           VARCHAR(50)              not null,
    scenario_id          BIGINT,
    motivation           VARCHAR(2000)            not null,
    status               VARCHAR(50)              not null,
    reviewed_by_user_id  BIGINT,
    reviewed_at          TIMESTAMP WITH TIME ZONE,
    review_note          VARCHAR(1500),
    created_at           TIMESTAMP WITH TIME ZONE not null
);

create index idx_accreditation_request_scope on accreditation_request (scope_type, scenario_id, created_at);

create table community_accreditation
(
    id                 BIGINT generated by default as identity primary key,
    user_id            BIGINT                   not null,
    scope_type         VARCHAR(50)              not null,
    scenario_id        BIGINT,
    granted_by_user_id BIGINT                   not null,
    granted_at         TIMESTAMP WITH TIME ZONE not null,
    note               VARCHAR(1500)
);

create unique index uq_community_accreditation_scope on community_accreditation (user_id, scope_type, scenario_id);