-- V5: Glottolog external Python pipeline (additive only).
-- Java owns admin config columns; Python owns operational pipeline state.
-- Flyway runs each version once: no IF NOT EXISTS on ALTER ADD COLUMN.

alter table glottolog_admin_settings
    add column frequency_days integer;

update glottolog_admin_settings
set frequency_days = case update_frequency
    when 'TWO_WEEKS' then 14
    when 'ONE_MONTH' then 30
    when 'THREE_MONTHS' then 90
    when 'SIX_MONTHS' then 180
    else null
end
where frequency_days is null;

alter table language
    add column present_in_latest_glottolog boolean;

alter table language
    add column last_seen_in_glottolog_at timestamp with time zone;

update language
set present_in_latest_glottolog = true
where present_in_latest_glottolog is null;

create table glottolog_pipeline_state
(
    id                              bigint primary key,
    next_run_at                     timestamp with time zone,
    last_check_at                   timestamp with time zone,
    last_success_at                 timestamp with time zone,
    current_status                  varchar(64) not null default 'IDLE',
    status_message                  varchar(2000),
    last_detected_checksum          varchar(128),
    last_downloaded_checksum        varchar(128),
    last_validated_checksum         varchar(128),
    last_imported_checksum          varchar(128),
    last_error                      varchar(4000),
    retry_count                     integer not null default 0,
    next_retry_at                   timestamp with time zone,
    lock_owner                      varchar(255),
    lock_expires_at                 timestamp with time zone,
    lock_heartbeat_at               timestamp with time zone,
    active_history_id               bigint,
    config_observed_at              timestamp with time zone,
    config_frequency_days           integer,
    config_auto_update_enabled      boolean,
    updated_at                      timestamp with time zone
);

insert into glottolog_pipeline_state (id, current_status, retry_count, updated_at)
values (1, 'IDLE', 0, current_timestamp);

create table glottolog_update_request
(
    id                      bigint generated by default as identity primary key,
    requested_by_username   varchar(255)             not null,
    requested_at            timestamp with time zone not null,
    status                  varchar(32)              not null,
    claimed_at              timestamp with time zone,
    claimed_by              varchar(255),
    heartbeat_at            timestamp with time zone,
    started_at              timestamp with time zone,
    finished_at             timestamp with time zone,
    history_id              bigint,
    error_message           varchar(4000)
);

create index idx_glottolog_update_request_status_requested
    on glottolog_update_request (status, requested_at);

alter table glottolog_update_history
    add column trigger_type varchar(32);

alter table glottolog_update_history
    add column pipeline_status varchar(64);

alter table glottolog_update_history
    add column remote_checksum varchar(128);

alter table glottolog_update_history
    add column imported_checksum varchar(128);

alter table glottolog_update_history
    add column retry_count integer;

alter table glottolog_update_history
    add column worker_id varchar(255);
