create table if not exists glottolog_admin_settings
(
    id                  bigint primary key,
    auto_update_enabled boolean                  not null,
    update_frequency    varchar(32)              not null,
    updated_at          timestamp with time zone,
    updated_by_username varchar(255)
);

create table if not exists glottolog_update_history
(
    id                   bigint generated by default as identity primary key,
    triggered_by_username varchar(255)             not null,
    status               varchar(32)              not null,
    started_at           timestamp with time zone not null,
    finished_at          timestamp with time zone,
    glottolog_version    varchar(64),
    download_duration_ms bigint,
    sync_duration_ms     bigint,
    source_rows          integer,
    selected_rows        integer,
    inserted_count       integer,
    updated_count        integer,
    unchanged_count      integer,
    database_count       bigint,
    error_message        varchar(4000)
);

create index if not exists idx_glottolog_update_history_started_at
    on glottolog_update_history (started_at desc);
