-- V8: Persist Glottolog admin email notifications (written by Python worker).
create table glottolog_notification
(
    id               bigint generated by default as identity primary key,
    created_at       timestamp with time zone not null,
    to_email         varchar(255)             not null,
    subject          varchar(500)             not null,
    body             varchar(8000)            not null,
    delivery_status  varchar(32)              not null,
    delivery_detail  varchar(1000),
    history_id       bigint,
    trigger_type     varchar(32),
    pipeline_status  varchar(64)
);

create index idx_glottolog_notification_created
    on glottolog_notification (created_at desc);
